Add SQL Server client/server implementation.
amat27/sql-ha pull request #6
Opened 2019-07-03 06:38 UTC by leexx227

2019-07-03 08:31 UTC, amat27 requested changes

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Interface/HeartBeatEntry.cs
> +        public static HeartBeatEntry Empty { get; } = new HeartBeatEntry(string.Empty, string.Empty, string.Empty, Convert.ToDateTime("1753-01-01 12:00:00.000"));
Is "1753-01-01 12:00:00.000" a special value? If yes, it's better that we deliberately save it as a static field

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/Program.cs
> +    class Program
Place sample client into separate project then library code

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +        public TimeSpan OperationTimeout { get; set; }
Timeout not used

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            string ConStr = "server=.;database=HighAvailabilityModule;Trusted_Connection=SSPI";
The connection string should have setter

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            SqlConnection con = new SqlConnection(ConStr);
Dispose the connection after use?

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            con.Open();
OpenAsync?

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            con.Open();
And exception handling

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            string ConStr = "server=.;database=HighAvailabilityModule;Trusted_Connection=SSPI";
Same hard-code problem here.

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            SqlConnection con = new SqlConnection(ConStr);
Same disposing issue here as above.

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            con.Open();
Same (async, exception handling) here

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +                    if (ReturnedEntry.Read())
else?

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Server.SQL/SQLstartup.sql
> +	DROP DATABASE HighAvailabilityModule;
As it's a DB, maybe we call it something other than "Module"? How about "HAWitness"?

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Server.SQL/SQLstartup.sql
> +		SET @TimeOut = 1000;
Can timeout be configurable?

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Server.SQL/SQLstartup.sql
> +	SET @now = CONVERT(DATETIME, GETDATE(), 21);
Is the `CONVERT` needed?

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Server.SQL/SQLstartup.sql
> +				INSERT INTO dbo.HeartBeatTable(uuid, utype, uname, timeStamp)
Optimistic concurrency fails here

2019-07-03 08:31 UTC, amat27 commented on HighAvailabilityModule.Server.SQL/SQLstartup.sql
> +		SELECT * FROM dbo.HeartBeatTable WHERE utype = NULL;
Don't need this?

2019-07-17 03:30 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            this.ConStr = "server=.;database=HighAvailabilityWitness;Trusted_Connection=SSPI;Connect Timeout=5";
The `Connect Timeout` is overwritten below?

2019-07-17 03:30 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +                throw new Exception($"[{this.Uuid}] Error occured when sending heartbeat entry: {ex.ToString()}");
Instead of wrapping it as another, trace the information down and just use `throw`

2019-07-17 03:30 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +                await comStr.ExecuteNonQueryAsync();
Do we need `await` these two operations?

2019-07-17 03:30 UTC, amat27 commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            SqlCommand comStr = new SqlCommand(StoredProcedure, con);
`SqlCommand` is also disposable?

2019-07-17 03:30 UTC, amat27 commented on HighAvailabilityModule.Server.SQL/SQLstartup.sql
> +		SET @TimeOut = 1000;
Still, can this time out be configurable, like an entry in a special table?

2019-07-17 03:30 UTC, amat27 commented on HighAvailabilityModule.Server.SQL/SQLstartup.sql
> +		SELECT TOP 1 * FROM dbo.HeartBeatTable WHERE utype=@utype;
Shall we specify the selected column here to prepare for compatibility

2019-07-18 08:58 UTC, amat27 approved these changes

2019-07-18 09:23 UTC, sunbinzhu approved these changes

2019-07-18 09:23 UTC, sunbinzhu commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            this.ConStr = "server=.;database=HighAvailabilityWitness;Trusted_Connection=SSPI;Connect Timeout=" + Convert.ToInt32(Math.Ceiling(this.OperationTimeout.TotalSeconds)).ToString();
Hard coded server and database?

2019-07-18 09:23 UTC, sunbinzhu commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            string StoredProcedure = "dbo.HeartBeat";
make it a const string

2019-07-18 09:23 UTC, sunbinzhu commented on HighAvailabilityModule.Client.SQL/SQLMembershipClient.cs
> +            string StoredProcedure = "dbo.GetHeartBeat";
Make the stored procedure names as const strings and move under the class or some common file if they will be used in other places.

2019-07-18 09:23 UTC, sunbinzhu commented on HighAvailabilityModule.Sample.SQLClient/Program.cs
> +                if (utype == "query")
case sensitive?

2019-07-18 09:23 UTC, sunbinzhu commented on HighAvailabilityModule.Sample.SQLClient/Program.cs
> +                        var primary = await client.GetHeartBeatEntryAsync(qtype);
how about the exception handling?

2019-07-19 02:07 UTC, merged